# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow file requires a free account on Semgrep.dev to
# manage rules, file ignores, notifications, and more.
#
# See https://semgrep.dev/docs

name: Semgrep

on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  schedule:
    - cron: '44 18 * * 2'

permissions:
  contents: read

jobs:
  semgrep:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      # Checkout project source
      - uses: actions/checkout@v3
      - name: Semgrep Scan
        id: scan
        #run: semgrep ci --config=auto --suppress-errors --sarif || true
        run: |
            semgrep \
              --sarif --output report.sarif \
              --config=semgrep_rules.yaml

      - name: Save Report as Pipeline Artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.sarif
          path: report.sarif

